In [55]:
from ucimlrepo import fetch_ucirepo
import pandas as pd

In [56]:
online_retail = fetch_ucirepo(id=352)

# data (as pandas dataframes)
X = online_retail.data.features 
y = online_retail.data.targets

In [57]:
ids = online_retail.data.ids
ids

       InvoiceNo StockCode
0         536365    85123A
1         536365     71053
2         536365    84406B
3         536365    84029G
4         536365    84029E
...          ...       ...
541904    581587     22613
541905    581587     22899
541906    581587     23254
541907    581587     23255
541908    581587     22138

[541909 rows x 2 columns]

In [58]:
df = ids.join(X)
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

In [59]:
df['InvoiceDate'].str.split()

0          [12/1/2010, 8:26]
1          [12/1/2010, 8:26]
2          [12/1/2010, 8:26]
3          [12/1/2010, 8:26]
4          [12/1/2010, 8:26]
                 ...
541904    [12/9/2011, 12:50]
541905    [12/9/2011, 12:50]
541906    [12/9/2011, 12:50]
541907    [12/9/2011, 12:50]
541908    [12/9/2011, 12:50]
Name: InvoiceDate, Length: 541909, dtype: object

### Understanding Missing Value

In [60]:
missing_values = df.isnull().sum()
print(missing_values)

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

### Handling Missing Value

In [61]:
## Drop Rows with Crucial Missing Data
df = df.dropna(subset=['CustomerID'])

## Fill Missing Descriptions (Fixing FutureWarning)
df['Description'] = df['Description'].fillna('Unknown Product')

## Check Duplicates
print(f"Duplicate Rows: {df.duplicated().sum()}")

## Remove Duplicates
df = df.drop_duplicates().reset_index(drop=True)

## Handling Incorrect or Invalid Data
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

## Convert Data Types for Consistency
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])

Duplicate Rows: 5225

In [47]:
df['Amount'] = df['UnitPrice'] * X['Quantity']
df['Date']= df['InvoiceDate'].transform(lambda x: x.split()[0])
df['Time'] = df['InvoiceDate'].transform(lambda x: x.split()[-1])

In [48]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
latest_date = df['InvoiceDate'].max()
df['Recency'] = (latest_date - df.groupby('CustomerID')['InvoiceDate'].transform('max')).dt.days

In [49]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Amount,Date,Time,Recency
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,12/1/2010,8:26,301.0
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,12/1/2010,8:26,301.0
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,12/1/2010,8:26,301.0
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,12/1/2010,8:26,301.0
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,12/1/2010,8:26,301.0
...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20,12/9/2011,12:50,0.0
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,12.60,12/9/2011,12:50,0.0
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,12/9/2011,12:50,0.0
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,16.60,12/9/2011,12:50,0.0
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,14.85,12/9/2011,12:50,0.0

In [52]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID,Amount,Recency
count,541909.000000,541909,541909.000000,406829.000000,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386,4.611114,15287.690570,17.987795,38.954140
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000,-168469.600000,0.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000,3.400000,3.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000,9.750000,15.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000,17.400000,40.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000,168469.600000,373.000000
std,218.081158,NaN,96.759853,1713.600303,378.810824,64.686233

In [63]:
CodeTypes = list(map(lambda codes: any(char.isdigit() for char in codes), df['StockCode']))
IrrelevantCodes = [i for i, v in enumerate(CodeTypes) if v == False]
IrrelevantCodes

[45,
 377,
 1087,
 1628,
 1639,
 3121,
 3719,
 3893,
 3955,
 3999,
 4330,
 4404,
 4523,
 4552,
 4718,
 4781,
 4818,
 5460,
 5483,
 6020,
 6077,
 6078,
 6742,
 6746,
 6766,
 6877,
 7003,
 7155,
 7514,
 7712,
 7734,
 8575,
 8811,
 8923,
 9381,
 9577,
 9664,
 9817,
 10597,
 10831,
 11626,
 11674,
 11676,
 11807,
 12605,
 12628,
 12648,
 12721,
 12784,
 12798,
 12838,
 12895,
 13644,
 13874,
 14241,
 14395,
 15159,
 16985,
 17229,
 18182,
 18233,
 18624,
 18643,
 18650,
 20460,
 21012,
 22544,
 22574,
 22741,
 22761,
 22858,
 22903,
 22930,
 22951,
 22997,
 23004,
 23019,
 23170,
 23284,
 23302,
 23534,
 23982,
 24116,
 24395,
 24494,
 24849,
 24923,
 25059,
 25326,
 25425,
 25497,
 25639,
 25919,
 26185,
 26219,
 26907,
 27152,
 27186,
 27826,
 28122,
 28394,
 28807,
 28880,
 28996,
 29160,
 29208,
 29298,
 29669,
 30233,
 30837,
 30979,
 31034,
 31037,
 31337,
 31650,
 31886,
 31926,
 32066,
 32282,
 32396,
 32466,
 32660,
 33079,
 33105,
 33180,
 33848,
 34054,
 34148,
 34177,
 34215,
 34316,
 34863,
 35366,
 35606,
 36212,
 36520,
 36586,
 36622,
 36847,
 36888,
 36973,
 37251,
 37375,
 37410,
 38022,
 38152,
 38297,
 38635,
 38810,
 39166,
 40033,
 40268,
 40500,
 40564,
 40750,
 40760,
 40937,
 41009,
 41304,
 42016,
 42048,
 42107,
 42362,
 42606,
 42811,
 43627,
 43665,
 43746,
 43955,
 44355,
 44439,
 44772,
 44948,
 45711,
 45745,
 45972,
 46266,
 46331,
 46427,
 46570,
 46781,
 47376,
 47559,
 47792,
 47804,
 47839,
 47901,
 48335,
 48490,
 48523,
 48592,
 48890,
 48956,
 48972,
 49383,
 49439,
 49573,
 49865,
 49962,
 51643,
 51969,
 52282,
 52341,
 52536,
 52620,
 52649,
 52671,
 52719,
 53133,
 53572,
 54529,
 54685,
 54743,
 55860,
 56126,
 56133,
 56636,
 56749,
 57225,
 57276,
 57303,
 57453,
 57829,
 58187,
 58442,
 58659,
 58747,
 59512,
 59745,
 59967,
 60068,
 60331,
 60353,
 60369,
 61423,
 62635,
 62687,
 62692,
 63082,
 63852,
 64193,
 64380,
 64571,
 64875,
 65639,
 65718,
 65753,
 65754,
 66069,
 66076,
 66079,
 66328,
 66741,
 66938,
 67186,
 67235,
 67321,
 67322,
 67323,
 67371,
 68690,
 68692,
 68927,
 68961,
 69091,
 69157,
 69336,
 69353,
 69509,
 69691,
 70108,
 70972,
 71002,
 71816,
 71897,
 72312,
 72660,
 72719,
 72784,
 73239,
 73325,
 73974,
 74211,
 75220,
 75221,
 75294,
 75369,
 75372,
 75864,
 76115,
 76179,
 76327,
 76342,
 76610,
 77250,
 78150,
 78556,
 78557,
 78701,
 78719,
 78720,
 78790,
 79307,
 79504,
 79689,
 80147,
 80165,
 80213,
 80325,
 80963,
 81438,
 81985,
 82192,
 82204,
 82219,
 82607,
 83430,
 83852,
 84142,
 84315,
 84316,
 84398,
 84468,
 84640,
 84824,
 84838,
 85057,
 85224,
 85252,
 85519,
 85806,
 86663,
 86847,
 86982,
 87066,
 87460,
 87547,
 87727,
 87774,
 87823,
 87832,
 88237,
 88479,
 88904,
 89027,
 89158,
 89361,
 89576,
 89587,
 89598,
 89710,
 91035,
 91649,
 91693,
 92043,
 92430,
 92598,
 92644,
 93460,
 93461,
 93743,
 93824,
 94021,
 94086,
 95055,
 95283,
 95458,
 95756,
 95757,
 95758,
 95759,
 95760,
 95868,
 96280,
 96453,
 98089,
 98388,
 98468,
 98878,
 99734,
 99991,
 100153,
 100731,
 101493,
 101737,
 101769,
 101792,
 102003,
 102156,
 102344,
 102778,
 104149,
 104378,
 104541,
 104555,
 105365,
 105533,
 105640,
 105785,
 105812,
 105865,
 105962,
 106281,
 106358,
 106398,
 106842,
 107732,
 108046,
 108355,
 108622,
 108871,
 109251,
 109523,
 109646,
 109839,
 110211,
 110254,
 111171,
 111549,
 111873,
 112005,
 112099,
 112149,
 112494,
 112580,
 112735,
 112820,
 113947,
 113959,
 114035,
 114196,
 114269,
 114726,
 114755,
 114999,
 115106,
 115330,
 115555,
 115976,
 116178,
 116241,
 116537,
 116597,
 116868,
 116925,
 117666,
 117692,
 118167,
 118332,
 118343,
 118434,
 118823,
 118925,
 119161,
 119636,
 120411,
 120491,
 120824,
 122079,
 122267,
 122443,
 122995,
 123367,
 123444,
 123895,
 124069,
 124243,
 124803,
 125741,
 125748,
 125750,
 126044,
 126104,
 126162,
 126341,
 126497,
 127039,
 127117,
 127550,
 127590,
 127736,
 127789,
 128741,
 129145,
 129347,
 129646,
 129975,
 130286,
 130861,
 130883,
 131929,
 132041,
 132080,
 132204,
 132497,
 132621,
 132719,
 133223,
 133348,
 133747,
 133766,
 134324,
 134333,
 135146,
 135490,
 136363,
 136816,
 136895,
 136932,
 137354,
 137381,
 137405,
 137496,
 137645,
 137726,
 138311,
 138312,
 138371,
 138392,
 138609,
 138660,
 139590,
 140083,
 140114,
 140172,
 140544,
 140648,
 140788,
 140803,
 141335,
 141525,
 141716,
 141773,
 141893,
 141932,
 142443,
 142890,
 143231,
 143249,
 143293,
 143405,
 143739,
 143852,
 143886,
 144391,
 145400,
 145483,
 145598,
 145658,
 146349,
 146421,
 146748,
 146877,
 147387,
 147483,
 147565,
 147708,
 148211,
 148533,
 148544,
 148569,
 148807,
 149616,
 150088,
 150164,
 150245,
 150291,
 150325,
 151196,
 151637,
 151656,
 152007,
 152150,
 152305,
 152393,
 152472,
 152736,
 152772,
 153091,
 153587,
 153681,
 153750,
 154881,
 154911,
 154996,
 154998,
 155043,
 155061,
 155113,
 155312,
 155489,
 155764,
 156598,
 156840,
 156865,
 156958,
 157218,
 158344,
 158629,
 158719,
 158970,
 159493,
 160021,
 160888,
 160930,
 161247,
 161789,
 161993,
 162267,
 162386,
 162523,
 162618,
 163211,
 163481,
 163604,
 163877,
 164372,
 164621,
 164733,
 165178,
 165214,
 165373,
 165608,
 166109,
 166322,
 166401,
 166914,
 167365,
 167515,
 168489,
 168907,
 169392,
 169475,
 170285,
 170424,
 170450,
 170500,
 170814,
 170921,
 170984,
 171343,
 172157,
 172181,
 172472,
 172851,
 173383,
 173856,
 174087,
 174137,
 174594,
 174605,
 175047,
 175363,
 175426,
 175688,
 176284,
 176515,
 176548,
 176563,
 176631,
 176826,
 176951,
 177191,
 177192,
 177284,
 178020,
 178467,
 178517,
 178690,
 178711,
 178903,
 178950,
 178983,
 179009,
 179584,
 179678,
 179740,
 180129,
 180132,
 180417,
 180836,
 181037,
 181238,
 181244,
 182295,
 182479,
 182521,
 182622,
 182758,
 182889,
 182931,
 183915,
 184567,
 185066,
 185445,
 186019,
 186061,
 186241,
 186313,
 186393,
 186808,
 186858,
 187020,
 187348,
 187776,
 188021,
 188752,
 189064,
 189631,
 189783,
 190202,
 190429,
 190662,
 191190,
 191223,
 191362,
 191592,
 192090,
 192219,
 192885,
 193299,
 193309,
 193595,
 193943,
 194949,
 194962,
 195695,
 196592,
 196698,
 196908,
 196941,
 197094,
 197215,
 197396,
 197480,
 198313,
 198341,
 198362,
 198376,
 198693,
 199933,
 200505,
 200522,
 200556,
 200712,
 200946,
 201156,
 201738,
 201872,
 201954,
 202109,
 202356,
 202408,
 202462,
 202552,
 203726,
 203832,
 204155,
 204806,
 205273,
 205649,
 205753,
 205876,
 206437,
 207042,
 207384,
 207942,
 208051,
 208255,
 208431,
 209462,
 209531,
 210026,
 210154,
 210588,
 211011,
 211247,
 211339,
 211850,
 212059,
 212876,
 213053,
 213369,
 213939,
 213991,
 214122,
 214153,
 214457,
 214458,
 214459,
 214590,
 214918,
 215271,
 215605,
 215852,
 216114,
 216859,
 217207,
 217775,
 218056,
 218216,
 218249,
 218298,
 218666,
 218955,
 218959,
 219130,
 219683,
 219735,
 219769,
 219918,
 220191,
 220213,
 220231,
 220258,
 220275,
 220549,
 220689,
 220906,
 221295,
 221491,
 221686,
 221744,
 222915,
 223024,
 223082,
 223297,
 223404,
 223425,
 223426,
 223561,
 223564,
 223844,
 224388,
 224404,
 225237,
 225566,
 225646,
 225738,
 225761,
 225955,
 226160,
 226224,
 226270,
 226823,
 226938,
 227487,
 227537,
 228351,
 228572,
 228633,
 228675,
 228887,
 229662,
 229884,
 229929,
 230109,
 230208,
 230361,
 230800,
 231054,
 231311,
 231378,
 231412,
 232244,
 232435,
 232514,
 232650,
 232701,
 232913,
 233154,
 233733,
 233994,
 234274,
 234491,
 234512,
 237464,
 238068,
 238198,
 238571,
 238764,
 240081,
 240132,
 240336,
 240941,
 241410,
 241432,
 241495,
 242133,
 242135,
 242838,
 243814,
 244396,
 244446,
 244999,
 245051,
 245109,
 245138,
 245240,
 245510,
 245618,
 245662,
 246051,
 246052,
 246293,
 246294,
 246309,
 246914,
 247013,
 247225,
 247325,
 247358,
 247614,
 247932,
 247971,
 248626,
 249101,
 249174,
 249222,
 249727,
 250138,
 250186,
 250657,
 250751,
 250832,
 250904,
 250941,
 250970,
 251029,
 251057,
 251163,
 251297,
 251310,
 251417,
 251591,
 251658,
 251923,
 251958,
 252056,
 253065,
 253111,
 253933,
 254011,
 254058,
 254730,
 254908,
 255178,
 256399,
 256436,
 256542,
 256543,
 256762,
 257000,
 257362,
 257803,
 258305,
 258407,
 258447,
 259065,
 259382,
 259492,
 260383,
 260655,
 261615,
 261689,
 261821,
 261964,
 262117,
 262380,
 262387,
 262655,
 262914,
 263145,
 263164,
 265501,
 266211,
 266465,
 266556,
 266726,
 266817,
 266818,
 266819,
 266915,
 268101,
 268287,
 268604,
 268717,
 269097,
 269145,
 269293,
 269652,
 270056,
 270594,
 271022,
 271054,
 271120,
 271232,
 272059,
 272365,
 272382,
 ...]