In [2]:
from pathlib import Path

import numpy as np
import pandas as pd
from ucimlrepo import fetch_ucirepo

In [3]:
print("Fetching Online Retail dataset from the UCI...")
online_retail = fetch_ucirepo(id=352)
online_retail

Fetching Online Retail dataset from the UCI...

{'data': {'ids':        InvoiceNo StockCode
  0         536365    85123A
  1         536365     71053
  2         536365    84406B
  3         536365    84029G
  4         536365    84029E
  ...          ...       ...
  541904    581587     22613
  541905    581587     22899
  541906    581587     23254
  541907    581587     23255
  541908    581587     22138

  [541909 rows x 2 columns],
  'features':                                 Description  Quantity      InvoiceDate  \
  0        WHITE HANGING HEART T-LIGHT HOLDER         6   12/1/2010 8:26
  1                       WHITE METAL LANTERN         6   12/1/2010 8:26
  2            CREAM CUPID HEARTS COAT HANGER         8   12/1/2010 8:26
  3       KNITTED UNION FLAG HOT WATER BOTTLE         6   12/1/2010 8:26
  4            RED WOOLLY HOTTIE WHITE HEART.         6   12/1/2010 8:26
  ...                                     ...       ...              ...
  541904          PACK OF 20 SPACEBOY NAPKINS        12  12/9/2011 12:50
  541905         CHILDREN'S APRON DOLLY GIRL          6  12/9/2011 12:50
  541906        CHILDRENS CUTLERY DOLLY GIRL          4  12/9/2011 12:50
  541907      CHILDRENS CUTLERY CIRCUS PARADE         4  12/9/2011 12:50
  541908        BAKING SET 9 PIECE RETROSPOT          3  12/9/2011 12:50

          UnitPrice  CustomerID         Country
  0            2.55     17850.0  United Kingdom
  1            3.39     17850.0  United Kingdom
  2            2.75     17850.0  United Kingdom
  3            3.39     17850.0  United Kingdom
  4            3.39     17850.0  United Kingdom
  ...           ...         ...             ...
  541904       0.85     12680.0          France
  541905       2.10     12680.0          France
  541906       4.15     12680.0          France
  541907       4.15     12680.0          France
  541908       4.95     12680.0          France

  [541909 rows x 6 columns],
  'targets': None,
  'original':        InvoiceNo StockCode                          Description  Quantity  \
  0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6
  1         536365     71053                  WHITE METAL LANTERN         6
  2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8
  3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6
  4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6
  ...          ...       ...                                  ...       ...
  541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12
  541905    581587     22899         CHILDREN'S APRON DOLLY GIRL          6
  541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL          4
  541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4
  541908    581587     22138        BAKING SET 9 PIECE RETROSPOT          3

              InvoiceDate  UnitPrice  CustomerID         Country
  0        12/1/2010 8:26       2.55     17850.0  United Kingdom
  1        12/1/2010 8:26       3.39     17850.0  United Kingdom
  2        12/1/2010 8:26       2.75     17850.0  United Kingdom
  3        12/1/2010 8:26       3.39     17850.0  United Kingdom
  4        12/1/2010 8:26       3.39     17850.0  United Kingdom
  ...                 ...        ...         ...             ...
  541904  12/9/2011 12:50       0.85     12680.0          France
  541905  12/9/2011 12:50       2.10     12680.0          France
  541906  12/9/2011 12:50       4.15     12680.0          France
  541907  12/9/2011 12:50       4.15     12680.0          France
  541908  12/9/2011 12:50       4.95     12680.0          France

  [541909 rows x 8 columns],
  'headers': Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
         'UnitPrice', 'CustomerID', 'Country'],
        dtype='str')},
 'metadata': {'uci_id': 352,
  'name': 'Online Retail',
  'repository_url': 'https://archive.ics.uci.edu/dataset/352/online+retail',
  'data_url': 'https://archive.ics.uci.edu/static/public/352/data.csv',
  'abstract': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.',
  'area': 'Business',
  'tasks': ['Classification', 'Clustering'],
  'characteristics': ['Multivariate', 'Sequential', 'Time-Series'],
  'num_instances': 541909,
  'num_features': 6,
  'feature_types': ['Integer', 'Real'],
  'demographics': [],
  'target_col': None,
  'index_col': ['InvoiceNo', 'StockCode'],
  'has_missing_values': 'no',
  'missing_values_symbol': None,
  'year_of_dataset_creation': 2015,
  'last_updated': 'Mon Oct 21 2024',
  'dataset_doi': '10.24432/C5BW33',
  'creators': ['Daqing Chen'],
  'intro_paper': {'ID': 361,
   'type': 'NATIVE',
   'title': 'Data mining for the online retail industry: A case study of RFM model-based customer segmentation using data mining',
   'authors': 'Daqing Chen, Sai Laing Sain, Kun Guo',
   'venue': 'Journal of Database Marketing and Customer Strategy Management, Vol. 19, No. 3',
   'year': 2012,
   'journal': None,
   'DOI': '10.1057/dbm.2012.17',
   'URL': 'https://www.semanticscholar.org/paper/e43a5a90fa33d419df42e485099f8f08badf2149',
   'sha': None,
   'corpus': None,
   'arxiv': None,
   'mag': None,
   'acl': None,
   'pmid': None,
   'pmcid': None},
  'additional_info': {'summary': 'This is a transactional data set which contains all the transactions occurring between 01/12/2010 and 09/12/2011 for a UK-based and registered non-store online retail.The company mainly sells unique all-occasion gifts. Many customers of the company are wholesalers.',
   'purpose': None,
   'funded_by': None,
   'instances_represent': None,
   'recommended_data_splits': None,
   'sensitive_data': None,
   'preprocessing_description': None,
   'variable_info': "InvoiceNo: Invoice number. Nominal, a 6-digit integral number uniquely assigned to each transaction. If this code starts with letter 'c', it indicates a cancellation. \nStockCode: Product (item) code. Nominal, a 5-digit integral number uniquely assigned to each distinct product.\nDescription: Product (item) name. Nominal.\nQuantity: The quantities of each product (item) per transaction. Numeric.\t\nInvoiceDate: Invoice Date and time. Numeric, the day and time when each transaction was generated.\nUnitPrice: Unit price. Numeric, Product price per unit in sterling.\nCustomerID: Customer number. Nominal, a 5-digit integral number uniquely assigned to each customer.\nCountry: Country name. Nominal, the name of the country where each customer resides. ",
   'citation': None}},
 'variables':           name     role         type demographic  \
 0    InvoiceNo       ID  Categorical        None
 1    StockCode       ID  Categorical        None
 2  Description  Feature  Categorical        None
 3     Quantity  Feature      Integer        None
 4  InvoiceDate  Feature         Date        None
 5    UnitPrice  Feature   Continuous        None
 6   CustomerID  Feature  Categorical        None
 7      Country  Feature  Categorical        None

                                          description     units missing_values
 0  a 6-digit integral number uniquely assigned to...       NaN             no
 1  a 5-digit integral number uniquely assigned to...       NaN             no
 2                                       product name       NaN             no
 3  the quantities of each product (item) per tran...       NaN             no
 4  the day and time when each transaction was gen...       NaN             no
 5                             product price per unit  sterling             no
 6  a 5-digit integral number uniquely assigned to...       NaN             no
 7  the name of the country where each customer re...       NaN             no  }

In [7]:
X = online_retail.data.features
X.head()

,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [8]:
ids = online_retail.data.ids
ids.head()

  InvoiceNo StockCode
0    536365    85123A
1    536365     71053
2    536365    84406B
3    536365    84029G
4    536365    84029E

In [9]:
df = ids.join(X)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [10]:
print(f"Raw shape: {df.shape}")
print("Missing values per column:\n", df.isnull().sum(), sep="")

Raw shape: (541909, 8)
Missing values per column:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

## Cleaning

In [12]:
# drop rows without CustomerID
df = df.dropna(subset=["CustomerID"]).copy()

# Fill missing product descriptions
df["Description"] = df["Description"].fillna("Unknown Product")

# Remove duplicate rows
dup_count = df.duplicated().sum()
print(f"Duplicate rows removed: {dup_count}")
df = df.drop_duplicates().reset_index(drop=True)

Duplicate rows removed: 5225

In [14]:
# Drop non-product / administratice StockCodes
#   (postage, manual adjustments, bank_charges, amazon fees, bad debt, etc)

bad_codes = {"POST", "D", "C2", "M", "BANK CHARGES", "AMAZONFEE", "DOT", "CRUK", "PADS", "B"}
df = df[~df['StockCode'].str.upper().isin(bad_codes)]

In [15]:
## Cancellations: InvoiceNo starting with 'C' = cancelled order
# Keep them in a separate frame for return behaviour features, then
# drop from the main transaction frame

df["InvoiceNo"] = df["InvoiceNo"].astype(str)
cancellations = df[df['InvoiceNo'].str.startswith("C")].copy()
df = df[~df['InvoiceNo'].str.startswith("C")]

In [16]:
# keep only strictly positive quantities and prices
df = df[(df['Quantity'] > 0) & (df['UnitPrice'] > 0)]

# Types
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df['CustomerID'] = df['CustomerID'].astype(int)

# Derived cols
df['Amount'] = df['Quantity'] * df['UnitPrice']
df['Date']   = df['InvoiceDate'].dt.date
df['Time']   = df['InvoiceDate'].dt.time
df['Hour']   = df['InvoiceDate'].dt.hour
df['DOW']    = df['InvoiceDate'].dt.day_name()
df['month']  = df['InvoiceDate'].dt.month

print(f"Clean transaction shape: {df.shape}")
print(f"Date range: {df['InvoiceDate'].min()} -> {df['InvoiceDate'].max()}")
print(f"Unique customers: {df['CustomerID'].nunique()}")
print(f"Unique invoices : {df['InvoiceNo'].nunique()}")
print(f"Countries       : {df['Country'].nunique()}")

Clean transaction shape: (391150, 14)
Date range: 2010-12-01 08:26:00 -> 2011-12-09 12:50:00
Unique customers: 4334
Unique invoices : 18402
Countries       : 37

## Feature Engineering

In [17]:
## Reference data = day after last transaction, the standard RFM conversion
snapshot_date = df["InvoiceDate"].max() + pd.Timedelta(days=1)

snapshot_date

Timestamp('2011-12-10 12:50:00')

In [18]:
# RFM core
rfm = df.groupby("CustomerID").agg(
    Recency  = ("InvoiceDate", lambda s: (snapshot_date - s.max()).days),
    Frequency = ("InvoiceNo", "nunique"),
    Monetary  = ("Amount", "sum"),
)

rfm

            Recency  Frequency  Monetary
CustomerID
12346           326          1  77183.60
12347             2          7   4310.00
12348            75          4   1437.24
12349            19          1   1457.55
12350           310          1    294.40
...             ...        ...       ...
18280           278          1    180.60
18281           181          1     80.82
18282             8          2    178.05
18283             4         16   2039.58
18287            43          3   1837.28

[4334 rows x 3 columns]

In [24]:
# extra behavioral features usefil for segmentation beyon pure RFM
extras = df.groupby("CustomerID").agg(
    TotalQuantity       = ("Quantity",  "sum"),
    UniqueProducts      = ("StockCode", "nunique"),
    AvgUnitPrice        = ("UnitPrice", "mean"),
    AvgBasketValue      = ("Amount",    "mean"),
    FirstPurchase       = ("InvoiceDate", "min"),
    LastPurchase        = ("InvoiceDate", "max")
)
extras['TenureDays'] = (extras['LastPurchase'] - extras['FirstPurchase'])
extras

,TotalQuantity,UniqueProducts,AvgUnitPrice,AvgBasketValue,FirstPurchase,LastPurchase,TenureDays
CustomerID,,,,,,,
12346,74215,1,1.040000,77183.600000,2011-01-18 10:01:00,2011-01-18 10:01:00,0 days 00:00:00
12347,2458,103,2.644011,23.681319,2010-12-07 14:57:00,2011-12-07 15:52:00,365 days 00:55:00
12348,2332,21,0.692963,53.231111,2010-12-16 19:09:00,2011-09-25 13:13:00,282 days 18:04:00
12349,630,72,4.237500,20.243750,2011-11-21 09:51:00,2011-11-21 09:51:00,0 days 00:00:00
12350,196,16,1.581250,18.400000,2011-02-02 16:01:00,2011-02-02 16:01:00,0 days 00:00:00
...,...,...,...,...,...,...,...
18280,45,10,4.765000,18.060000,2011-03-07 09:52:00,2011-03-07 09:52:00,0 days 00:00:00
18281,54,7,5.622857,11.545714,2011-06-12 10:53:00,2011-06-12 10:53:00,0 days 00:00:00
18282,103,12,5.199167,14.837500,2011-08-05 13:35:00,2011-12-02 11:43:00,118 days 22:08:00
18283,1355,262,1.625007,2.836690,2011-01-06 14:14:00,2011-12-06 12:02:00,333 days 21:48:00
18287,1586,59,1.493571,26.246857,2011-05-22 10:39:00,2011-10-28 09:29:00,158 days 22:50:00

In [22]:
# Average order value (per invoice) and items per order
order_totals = df.groupby(['CustomerID', 'InvoiceNo']).agg(
    order_value = ("Amount", "sum"),
    order_items = ("Quantity", "sum"),
).reset_index()

order_totals

       CustomerID InvoiceNo  order_value  order_items
0           12346    541431     77183.60        74215
1           12347    537626       711.79          319
2           12347    542237       475.39          315
3           12347    549222       636.25          483
4           12347    556201       382.52          196
...           ...       ...          ...          ...
18397       18283    579673       220.31          132
18398       18283    580872       208.00          142
18399       18287    554065       765.28          488
18400       18287    570715      1001.32          990
18401       18287    573167        70.68          108

[18402 rows x 4 columns]

In [23]:
per_order = order_totals.groupby("CustomerID").agg(
    AvgOrderValue = ("order_value", "mean"),
    AvgOrderItems = ("order_items", "mean"),
)

per_order

            AvgOrderValue  AvgOrderItems
CustomerID
12346        77183.600000   74215.000000
12347          615.714286     351.142857
12348          359.310000     583.000000
12349         1457.550000     630.000000
12350          294.400000     196.000000
...                   ...            ...
18280          180.600000      45.000000
18281           80.820000      54.000000
18282           89.025000      51.500000
18283          127.473750      84.687500
18287          612.426667     528.666667

[4334 rows x 2 columns]

In [25]:
cancellations["CustomerID"] = pd.to_numeric(
    cancellations["CustomerID"], errors="coerce"
)

returns = (
    cancellations.dropna(subset=['CustomerID'])
    .assign(CustomerID=lambda d: d["CustomerID"].astype(int))
    .groupby("CustomerID")
    .agg(ReturnInvoices=("InvoiceNo", "nunique"))
)

returns

            ReturnInvoices
CustomerID
12346                    1
12352                    1
12359                    2
12362                    3
12375                    1
...                    ...
18272                    1
18274                    1
18276                    2
18277                    1
18282                    1

[1534 rows x 1 columns]

In [26]:
# Dominant country per customer (mode)
country = (
    df.groupby("CustomerID")["Country"]
    .agg(lambda s: s.mode().iat[0])
    .rename("Country")
)
country

CustomerID
12346    United Kingdom
12347           Iceland
12348           Finland
12349             Italy
12350            Norway
              ...
18280    United Kingdom
18281    United Kingdom
18282    United Kingdom
18283    United Kingdom
18287    United Kingdom
Name: Country, Length: 4334, dtype: str

In [28]:
# Assemble
customer_features = (
    rfm
    .join(extras)
    .join(per_order)
    .join(returns)
    .join(country)
)

customer_features.head()

,Recency,Frequency,Monetary,TotalQuantity,UniqueProducts,AvgUnitPrice,AvgBasketValue,FirstPurchase,LastPurchase,TenureDays,AvgOrderValue,AvgOrderItems,ReturnInvoices,Country
CustomerID,,,,,,,,,,,,,,
12346,326,1,77183.60,74215,1,1.040000,77183.600000,2011-01-18 10:01:00,2011-01-18 10:01:00,0 days 00:00:00,77183.600000,74215.000000,1.0,United Kingdom
12347,2,7,4310.00,2458,103,2.644011,23.681319,2010-12-07 14:57:00,2011-12-07 15:52:00,365 days 00:55:00,615.714286,351.142857,NaN,Iceland
12348,75,4,1437.24,2332,21,0.692963,53.231111,2010-12-16 19:09:00,2011-09-25 13:13:00,282 days 18:04:00,359.310000,583.000000,NaN,Finland
12349,19,1,1457.55,630,72,4.237500,20.243750,2011-11-21 09:51:00,2011-11-21 09:51:00,0 days 00:00:00,1457.550000,630.000000,NaN,Italy
12350,310,1,294.40,196,16,1.581250,18.400000,2011-02-02 16:01:00,2011-02-02 16:01:00,0 days 00:00:00,294.400000,196.000000,NaN,Norway

In [30]:
customer_features["ReturnInvoices"] = customer_features["ReturnInvoices"].fillna(0).astype(int)
customer_features["ReturnRate"] = (
    customer_features["ReturnInvoices"] /
    (customer_features["Frequency"] + customer_features["ReturnInvoices"])
)
customer_features.head()

,Recency,Frequency,Monetary,TotalQuantity,UniqueProducts,AvgUnitPrice,AvgBasketValue,FirstPurchase,LastPurchase,TenureDays,AvgOrderValue,AvgOrderItems,ReturnInvoices,Country,ReturnRate
CustomerID,,,,,,,,,,,,,,,
12346,326,1,77183.60,74215,1,1.040000,77183.600000,2011-01-18 10:01:00,2011-01-18 10:01:00,0 days 00:00:00,77183.600000,74215.000000,1,United Kingdom,0.5
12347,2,7,4310.00,2458,103,2.644011,23.681319,2010-12-07 14:57:00,2011-12-07 15:52:00,365 days 00:55:00,615.714286,351.142857,0,Iceland,0.0
12348,75,4,1437.24,2332,21,0.692963,53.231111,2010-12-16 19:09:00,2011-09-25 13:13:00,282 days 18:04:00,359.310000,583.000000,0,Finland,0.0
12349,19,1,1457.55,630,72,4.237500,20.243750,2011-11-21 09:51:00,2011-11-21 09:51:00,0 days 00:00:00,1457.550000,630.000000,0,Italy,0.0
12350,310,1,294.40,196,16,1.581250,18.400000,2011-02-02 16:01:00,2011-02-02 16:01:00,0 days 00:00:00,294.400000,196.000000,0,Norway,0.0

In [31]:
for col in["Recency", "Frequency", "Monetary",
          "TotalQuantity", "UniqueProducts", "AvgOrderValue"]:
    customer_features[f'log_{col}'] = np.log1p(customer_features[col])

customer_features = customer_features.reset_index()
customer_features

,CustomerID,Recency,Frequency,Monetary,TotalQuantity,UniqueProducts,AvgUnitPrice,AvgBasketValue,FirstPurchase,LastPurchase,...,AvgOrderItems,ReturnInvoices,Country,ReturnRate,log_Recency,log_Frequency,log_Monetary,log_TotalQuantity,log_UniqueProducts,log_AvgOrderValue
0,12346,326,1,77183.60,74215,1,1.040000,77183.600000,2011-01-18 10:01:00,2011-01-18 10:01:00,...,74215.000000,1,United Kingdom,0.500000,5.789960,0.693147,11.253955,11.214735,0.693147,11.253955
1,12347,2,7,4310.00,2458,103,2.644011,23.681319,2010-12-07 14:57:00,2011-12-07 15:52:00,...,351.142857,0,Iceland,0.000000,1.098612,2.079442,8.368925,7.807510,4.644391,6.424406
2,12348,75,4,1437.24,2332,21,0.692963,53.231111,2010-12-16 19:09:00,2011-09-25 13:13:00,...,583.000000,0,Finland,0.000000,4.330733,1.609438,7.271175,7.754910,3.091042,5.886965
3,12349,19,1,1457.55,630,72,4.237500,20.243750,2011-11-21 09:51:00,2011-11-21 09:51:00,...,630.000000,0,Italy,0.000000,2.995732,0.693147,7.285198,6.447306,4.290459,7.285198
4,12350,310,1,294.40,196,16,1.581250,18.400000,2011-02-02 16:01:00,2011-02-02 16:01:00,...,196.000000,0,Norway,0.000000,5.739793,0.693147,5.688330,5.283204,2.833213,5.688330
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4329,18280,278,1,180.60,45,10,4.765000,18.060000,2011-03-07 09:52:00,2011-03-07 09:52:00,...,45.000000,0,United Kingdom,0.000000,5.631212,0.693147,5.201806,3.828641,2.397895,5.201806
4330,18281,181,1,80.82,54,7,5.622857,11.545714,2011-06-12 10:53:00,2011-06-12 10:53:00,...,54.000000,0,United Kingdom,0.000000,5.204007,0.693147,4.404522,4.007333,2.079442,4.404522
4331,18282,8,2,178.05,103,12,5.199167,14.837500,2011-08-05 13:35:00,2011-12-02 11:43:00,...,51.500000,1,United Kingdom,0.333333,2.197225,1.098612,5.187665,4.644391,2.564949,4.500087
4332,18283,4,16,2039.58,1355,262,1.625007,2.836690,2011-01-06 14:14:00,2011-12-06 12:02:00,...,84.687500,0,United Kingdom,0.000000,1.609438,2.833213,7.620989,7.212294,5.572154,4.855725
4333,18287,43,3,1837.28,1586,59,1.493571,26.246857,2011-05-22 10:39:00,2011-10-28 09:29:00,...,528.666667,0,United Kingdom,0.000000,3.784190,1.386294,7.516586,7.369601,4.094345,6.419061

In [80]:
# Save
# ---------------------------------------------------------------------------
import os
out_dir = Path.cwd().parent
os.makedirs(out_dir / "data", exist_ok=True)
df.to_csv(out_dir/ "data" / "online_retail_clean.csv", index=False)
customer_features.to_csv(out_dir / "data" / "customer_features.csv", index=False)

print("\nSaved:")
print(" ", out_dir / "data" / "online_retail_clean.csv", df.shape)
print(" ", out_dir / "data" / "customer_features.csv", customer_features.shape)

print("\nCustomer feature preview:")
print(customer_features.head())
print("\nSummary stats:")
print(customer_features[["Recency", "Frequency", "Monetary",
                         "AvgOrderValue", "TenureDays", "ReturnRate"]]
      .describe().round(2))

Saved:
  /mnt/c/Users/anish/CSP_571_FinalProj/data/online_retail_clean.csv (391150, 14)
  /mnt/c/Users/anish/CSP_571_FinalProj/data/customer_features.csv (4334, 22)

Customer feature preview:
   CustomerID  Recency  Frequency  Monetary  TotalQuantity  UniqueProducts  \
0       12346      326          1  77183.60          74215               1
1       12347        2          7   4310.00           2458             103
2       12348       75          4   1437.24           2332              21
3       12349       19          1   1457.55            630              72
4       12350      310          1    294.40            196              16

   AvgUnitPrice  AvgBasketValue       FirstPurchase        LastPurchase  ...  \
0      1.040000    77183.600000 2011-01-18 10:01:00 2011-01-18 10:01:00  ...
1      2.644011       23.681319 2010-12-07 14:57:00 2011-12-07 15:52:00  ...
2      0.692963       53.231111 2010-12-16 19:09:00 2011-09-25 13:13:00  ...
3      4.237500       20.243750 2011-11-21 09:51:00 2011-11-21 09:51:00  ...
4      1.581250       18.400000 2011-02-02 16:01:00 2011-02-02 16:01:00  ...

   AvgOrderItems  ReturnInvoices         Country  ReturnRate log_Recency  \
0   74215.000000               1  United Kingdom         0.5    5.789960
1     351.142857               0         Iceland         0.0    1.098612
2     583.000000               0         Finland         0.0    4.330733
3     630.000000               0           Italy         0.0    2.995732
4     196.000000               0          Norway         0.0    5.739793

   log_Frequency  log_Monetary  log_TotalQuantity  log_UniqueProducts  \
0       0.693147     11.253955          11.214735            0.693147
1       2.079442      8.368925           7.807510            4.644391
2       1.609438      7.271175           7.754910            3.091042
3       0.693147      7.285198           6.447306            4.290459
4       0.693147      5.688330           5.283204            2.833213

   log_AvgOrderValue
0          11.253955
1           6.424406
2           5.886965
3           7.285198
4           5.688330

[5 rows x 22 columns]

Summary stats:
       Recency  Frequency   Monetary  AvgOrderValue  TenureDays  ReturnRate
count  4334.00    4334.00    4334.00        4334.00     4334.00     4334.00
mean     92.70       4.25    2015.97         415.48      130.29        0.10
std     100.18       7.63    8903.67        1800.90      132.09        0.16
min       1.00       1.00       3.75           3.75        0.00        0.00
25%      18.00       1.00     304.24         177.20        0.00        0.00
50%      51.00       2.00     662.56         289.56       92.00        0.00
75%     143.00       5.00    1631.62         423.41      252.00        0.20
max     374.00     206.00  279138.02       84236.25      373.00        0.75